exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
extensions:
  health_check: {}
  memory_ballast: {}
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 1638
    spike_limit_mib: 512
receivers:
  otlp:
    protocols:
      grpc: null
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    traces:
      exporters:
      - jaeger
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp