version: "3.7"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports:
      - 14250
      - 16686:16686

  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 6666:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - db
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_ENABLE_FEATURE: tracing
      PROMSCALE_OTLP_GRPC_SERVER_LISTEN_ADDRESS: ":9202"
      PROMSCALE_TELEMETRY_TRACE_JAEGER_ENDPOINT: "http://otel-collector:14268/api/traces"
      PROMSCALE_TELEMETRY_TRACE_SAMPLING_RATIO: "0.1"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - 4317:4317
      - 14268:14268
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    depends_on:
      - jaeger
      - promscale
